# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dime Budget App

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checking out
      uses: actions/checkout@v2

    - name: Installing Dependencies
      run: npm install

    - name: Setting Timestamp
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        format: 'YYYY-MM-DD-HH-mm-ss'
        
    - name: Checking Release Directory
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "~/vue-releases"
      env:
        TIMESTAMP: "${{ steps.time.outputs.time }}"
        
    - if: steps.check_files.outputs.file_exists == 'false'
      shell: bash
      run: |
        mkdir -p ~/vue-releases
    
    - name: Building App
      shell: bash
      run: |
        mkdir -p $HOME/test
        echo "$HOME/vue-releases/$TIMESTAMP"
        ./node_modules/.bin/vue-cli-service build --dest=~/vue-releases/$TIMESTAMP --no-clean
      
    - name: Setting Current Build
      shell: bash
      run: |
        ln -sfn ~/vue-releases/$TIMESTAMP current
