# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dime Budget App

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checking out
      uses: actions/checkout@v2
      
    - name: Node Setup
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Set Environment
      run: |
        touch .env.production
        echo VUE_APP_TOKEN=${{ secrets.VUE_APP_TOKEN }} >> .env.production
        echo VUE_APP_API_DOMAIN=${{ secrets.VUE_APP_API_DOMAIN }} >> .env.production
        echo VUE_APP_VERIFY=${{ secrets.VUE_APP_VERIFY }} >> .env.production
        echo VUE_APP_SECRET_KEY=${{ secrets.VUE_APP_SECRET_KEY }} >> .env.production

    - name: Installing Dependencies
      run: npm install

    - name: Setting Timestamp
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        format: 'YYYY-MM-DD-HH-mm-ss'
        
    - name: Checking Release Directory
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "~/vue-releases"
        
    - if: steps.check_files.outputs.file_exists == 'false'
      shell: bash
      run: |
        mkdir -p $HOME/vue-releases
    
    - name: Building App
      shell: bash
      env:
        TIME: "${{ steps.time.outputs.time }}"
      run: |
        NODE_ENV=production
        $GITHUB_WORKSPACE/node_modules/.bin/vue-cli-service build --dest=$HOME/vue-releases/$TIME --no-clean
      
    - name: Setting Current Build
      shell: bash
      env:
        TIME: "${{ steps.time.outputs.time }}"
      run: |
        ln -sfn $HOME/vue-releases/$TIME $HOME/vue-releases/current
